## Topics
topic_imu: "/sensor_platform/imu"
topic_baro_altimeter: "/sensor_platform/baro"
topic_radar_scan: "/sensor_platform/radar/scan"

## Extrinsic calibration of body frame to radar frame
# translation of radar frame expressed in body frame
p_RinI_x: 0.01
p_RinI_y: 0.10
p_RinI_z: 0.06

# rotation radar frame to body frame
q_RtoI_w: -0.01185
q_RtoI_x:  0.36648
q_RtoI_y:  0.93033
q_RtoI_z:  0.00560

# length of each radar frame (="exposure time" of radar scan) in milliseconds
radar_frame_ms: 18.5

# nominal radar rate
radar_rate: 10
